name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf

      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984
        with:
          python-version: "3.x"

      - name: deps
        run: python -m pip install -U build

      - name: build
        run: python -m build

      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: ./dist/
          if-no-files-found: warn

  release-pypi:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Download artifacts diretories # goes to current working directory
        uses: actions/download-artifact@v3

      - name: publish
        uses: pypa/gh-action-pypi-publish@d7edd4c95736a5bc1260d38b5523f5d24338bc25
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: built-packages/

  release-github:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload release assets.
      contents: write
    steps:
      - name: Download artifacts diretories # goes to current working directory
        uses: actions/download-artifact@v3

      - name: Upload artifacts to github
        # Confusingly, this action also supports updating releases, not
        # just creating them. This is what we want here, since we've manually
        # created the release that triggered the action.
        uses: softprops/action-gh-release@v1
        with:
          files: built-packages/*
